services:
  - type: web
    name: whatifbot
    runtime: python
    region: oregon
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: WEBHOOK_URL
        value: ""  # Leave blank for now, you'll set this manually in dashboard later
